# Numbers

In [1]:
import numpy as np
import pandas as pd

In [2]:
2 ** 65

36893488147419103232

In [3]:
np.int64(2) ** 10

1024

In [4]:
np.int64(2) ** 65

0

In [5]:
3 / 2  # Python3 returns float while Python2 returns int like // of Python3

1.5

In [6]:
3 // 2

1

In [7]:
np.int(3) / np.int(2)

1.5

In [8]:
np.int(3) // np.int(2)

1

# Collections

## Built-in Lists

In [9]:
# List Literals
[1, 2, 3]

[1, 2, 3]

In [10]:
# List Comprehensions
r0_2 = range(3)  # [0, 3) == [0, 2]
[x + 1 for x in r0_2]

[1, 2, 3]

In [11]:
# Each range can be used many times
[x + 1 for x in r0_2]

[1, 2, 3]

In [12]:
r0_2

range(0, 3)

In [13]:
# List Constructors
list(range(1, 4))  # [1, 4) == [1, 3]

[1, 2, 3]

In [14]:
list([1, 2, 3])

[1, 2, 3]

In [15]:
# Lists are mutable
l = [1, 2, 3]
l[0] = 0
l

[0, 2, 3]

In [16]:
# Unpacking lists
l0, l1, l2 = [1, 2, 3]
print(l0, l1, l2)

1 2 3


## Built-in Tuples

In [17]:
# Tuple Literals
t = (1, 2, 3)
t

(1, 2, 3)

In [18]:
# No Tuple Comprehensions but they are generators
generator = (x + 1 for x in range(3))
generator

<generator object <genexpr> at 0x1102a6f68>

In [19]:
# Tuple Constructors
tuple(generator)

(1, 2, 3)

In [20]:
# Each generator can be used only once!
tuple(generator)

()

In [21]:
tuple(range(1,4))

(1, 2, 3)

In [22]:
tuple([1, 2, 3])

(1, 2, 3)

In [23]:
tuple(t)

(1, 2, 3)

In [24]:
t[0]

1

In [25]:
# Tuples are immutable
t[0] = 0  # TypeError: 'tuple' object does not support item assignment

TypeError: 'tuple' object does not support item assignment

In [26]:
# Unpacking Tuples
t0, t1, t2 = t
print(t0, t1, t2)

1 2 3


In [27]:
# Pythonic Swap
t0, t1 = t1, t0
print(t0, t1, t2)

2 1 3


## Built-in Strings


In [28]:
# String Literals
"Useful for single quotes (')"

"Useful for single quotes (')"

In [29]:
'Useful for double quotes (")'

'Useful for double quotes (")'

In [30]:
'Have to escape when mixing of double quotes (") and single quotes (\')'

'Have to escape when mixing of double quotes (") and single quotes (\')'

In [31]:
f'Python 3.6+ supports String Interpolation: the tuple t = {t}'

In [32]:
'''
This is a longer string that
spans multiple lines
'''

'\nThis is a longer string that\nspans multiple lines\n'

In [33]:
r'this\has\no\special\characters'

'this\\has\\no\\special\\characters'

In [34]:
txt = 'abcd'
txt[0]

'a'

In [35]:
txt[1:3]

'bc'

In [36]:
txt[1:]

'bcd'

In [37]:
txt[:3]

In [38]:
# Strings are immutable
txt[0] = 'z'  # TypeError: 'str' object does not support item assignment

TypeError: 'str' object does not support item assignment

In [39]:
txt + txt

'abcdabcd'

## Built-in Sets

In [40]:
# Set Literals
s = {1, 2, 3, 2, 1}
s

{1, 2, 3}

In [41]:
# Set Comprehensions
{x + 1 for x in range(3)}

{1, 2, 3}

In [42]:
# Set Constructors
set(range(1, 4))

{1, 2, 3}

In [43]:
set([1, 2, 3])

{1, 2, 3}

In [44]:
set(t)

{1, 2, 3}

In [45]:
set(s)

{1, 2, 3}

In [46]:
s[0]  # TypeError: 'set' object does not support indexing

TypeError: 'set' object does not support indexing

In [47]:
# Unpacking Sets
s0, s1, s2 = s
print(s0, s1, s2)

In [48]:
# Sets are mutable
s.remove(1)
s

{2, 3}

In [49]:
t.remove(1)  # AttributeError: 'tuple' object has no attribute 'remove'

AttributeError: 'tuple' object has no attribute 'remove'

## Built-in Dict

In [50]:
# Dict Literals
d = {0: 1, 1: 2, 2: 3}
d

{0: 1, 1: 2, 2: 3}

In [51]:
# Dict Comprehensions
{x: x + 1 for x in range(3)}

{0: 1, 1: 2, 2: 3}

In [52]:
{index: value for index, value in enumerate(t)}

{0: 1, 1: 2, 2: 3}

In [53]:
{x: None for x in range(10) if x % 2 == 0}

{0: None, 2: None, 4: None, 6: None, 8: None}

In [54]:
# Dict Constructors
dict(zip(range(3), range(1, 4)))

{0: 1, 1: 2, 2: 3}

In [55]:
dict(t)  # TypeError: cannot convert dictionary update sequence element #0 to a sequence

TypeError: cannot convert dictionary update sequence element #0 to a sequence

In [56]:
dict(enumerate(t))

{0: 1, 1: 2, 2: 3}

In [57]:
dict([(0, 1), (1, 2), (2, 3)])

{0: 1, 1: 2, 2: 3}

In [58]:
dict(d)

{0: 1, 1: 2, 2: 3}

In [59]:
d[0]

1

In [60]:
# Unpacking Dicts => Keys
k0, k1, k2 = d
print(k0, k1, k2)

0 1 2


In [61]:
d0, d1, d2 = d.items()
print(d0, d1, d2)

(0, 1) (1, 2) (2, 3)


In [62]:
# Dicts are mutable
d[0] = 10
d

In [63]:
d.pop(0)
d

{1: 2, 2: 3}

## NumPy Arrays

In [64]:
# Array Constructors
a = np.array([1,2,3])
a

array([1, 2, 3])

In [65]:
a.shape

(3,)

In [66]:
# Creating Arrays 
np.arange(1, 4)

array([1, 2, 3])

In [67]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [68]:
v = np.ones(3, dtype=int).reshape(1, 3)
v

array([[1, 1, 1]])

In [69]:
v.shape

(1, 3)

In [70]:
np.linspace(1, 10, 3, dtype=int)

array([ 1,  5, 10])

In [71]:
np.linspace(1, 3, 3, dtype=int)

array([1, 2, 3])

In [72]:
# Array Broadcasting
np.array(range(3)) + 1

array([1, 2, 3])

In [73]:
np.arange(3) + 1

array([1, 2, 3])

In [74]:
a - 1

array([0, 1, 2])

In [75]:
1 - a

array([ 0, -1, -2])

In [76]:
a * 2 

array([2, 4, 6])

In [77]:
a / 2

array([0.5, 1. , 1.5])

In [78]:
1 / a

array([1.        , 0.5       , 0.33333333])

In [79]:
a ** 2

array([1, 4, 9])

In [80]:
2 ** a

array([2, 4, 8])

In [81]:
# Array Operations
a + a

array([2, 4, 6])

In [82]:
a - a

array([0, 0, 0])

In [83]:
a * a

array([1, 4, 9])

In [84]:
a / a

array([1., 1., 1.])

In [85]:
a ** a

array([ 1,  4, 27])

In [86]:
# Array Indexing & Slicing
a[0]

1

In [87]:
a[-1]

In [88]:
a[1:]

array([2, 3])

In [89]:
a[:2]

array([1, 2])

In [90]:
a[:]  # not a copy like list!

array([1, 2, 3])

In [91]:
a[0:3]

array([1, 2, 3])

In [92]:
a[0:3:2]

array([1, 3])

In [93]:
a[::-1]

array([3, 2, 1])

In [94]:
# [:] for lists is a copy
l = [1, 2, 3]
l

[1, 2, 3]

In [95]:
copy = l[:]
copy

[1, 2, 3]

In [96]:
copy[0] = -1
print('l =', l)
print('copy =', copy)

l = [1, 2, 3]
copy = [-1, 2, 3]


In [97]:
# 2-D Arrays
m = np.arange(6).reshape(2, 3)
m

array([[0, 1, 2],
       [3, 4, 5]])

In [98]:
m[1] += 7
m

array([[ 0,  1,  2],
       [10, 11, 12]])

In [99]:
m[1][2]

12

In [100]:
m[1, 2]

12

In [101]:
m[:2, 1]

array([ 1, 11])

In [102]:
m[1, 1:]

array([11, 12])

In [103]:
m[:2, 1:]

array([[ 1,  2],
       [11, 12]])

In [104]:
m[:, 0]

array([ 0, 10])

In [105]:
m[[0, 1]]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [106]:
m[:,[0, 2]]

array([[ 0,  2],
       [10, 12]])

In [107]:
m[[1],[0, 2]]

array([10, 12])

In [108]:
m.T

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12]])

In [109]:
import random
data = [random.random() for _ in range(10000000)]

In [110]:
adata = np.array(data)

In [111]:
sdata = pd.Series(adata)

In [112]:
def sum(X):
    s = 0
    for x in X:
        s += x
    return s


print('loop answer =', sum(data))

loop answer = 5001055.537505497


In [113]:
print('np answer =', adata.sum())

np answer = 5001055.537505776


In [114]:
print('pd Series answer =', sdata.sum())

pd Series answer = 5001055.537505776


In [115]:
%timeit  sum(data)

1 loop, best of 3: 325 ms per loop


In [116]:
%timeit adata.sum()

100 loops, best of 3: 6.84 ms per loop


### Array Processing

In [117]:
A = np.array([1, 2, 3, 4])
B = np.array([100, 200, 300, 400])
conditions = np.array([True, True, False, False])

In [118]:
# list comprehension
[ a if cond else b for a, b, cond in zip(A, B, conditions) ]

[1, 2, 300, 400]

In [119]:
np.where(conditions, A, B)

array([  1,   2, 300, 400])

In [120]:
np.where(A < 3, 0, 1)

array([0, 0, 1, 1])

In [121]:
rnds = np.random.rand(3)
rnds

array([0.22170934, 0.69354648, 0.33163616])

In [122]:
am = rnds.argmax()
am, rnds[am]

(1, 0.6935464808401971)

In [123]:
m.sum()

36

In [124]:
m.sum(axis=0) # rows

array([10, 12, 14])

In [125]:
m.sum(axis=1) # columns

array([ 3, 33])

## Pandas Series

In [126]:
d_data = {'d':4, 'b':7, 'a':-5, 'c':3}
ps = pd.Series(d_data)
ps

a   -5
b    7
c    3
d    4
dtype: int64

In [127]:
np.array(d_data)

array({'d': 4, 'b': 7, 'a': -5, 'c': 3}, dtype=object)

In [128]:
pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

d    4
b    7
a   -5
c    3
dtype: int64

In [129]:
ps.values

array([-5,  7,  3,  4])

In [130]:
ps.index

In [131]:
'a' in ps

In [132]:
'z' in ps

False

In [133]:
ps.to_dict()

{'a': -5, 'b': 7, 'c': 3, 'd': 4}

In [134]:
ps.sum() # and other methods like in np.array

9

## Panda DataFrames

In [135]:
df = pd.read_csv('https://raw.githubusercontent.com/chirayukong/infsci2725-spring-2018/master/assignment-01/HallOfFame.csv')
df.columns = ['playerID', 'yearID', 'votedBy', 'ballots', 'needed', 'votes', 'inducted', 'category']
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4120 entries, 0 to 4119
Data columns (total 8 columns):
playerID    4120 non-null object
yearID      4120 non-null int64
votedBy     4120 non-null object
ballots     4120 non-null int64
needed      4120 non-null int64
votes       4120 non-null int64
inducted    4120 non-null object
category    4120 non-null object
dtypes: int64(4), object(4)
memory usage: 257.6+ KB


<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>playerID</th>
      <th>yearID</th>
      <th>votedBy</th>
      <th>ballots</th>
      <th>needed</th>
      <th>votes</th>
      <th>inducted</th>
      <th>category</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>connoto99</td>
      <td>1953</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
    </tr>
    <tr>
      <th>1</th>
      <td>klembi99</td>
      <td>1953</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
    </tr>
    <tr>
      <th>2</th>
      <td>evansbi99</td>
      <td>1973</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
    </tr>
    <tr>
      <th>3</th>
      <td>conlajo01</td>
      <td>1974</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
    </tr>
    <tr>
      <th>4</th>
      <td>hubbaca99</td>
      <td>1976</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
    </tr>
  </tbody>
</table>
</div>

In [136]:
df.keys()

Index(['playerID', 'yearID', 'votedBy', 'ballots', 'needed', 'votes',
       'inducted', 'category'],
      dtype='object')

In [137]:
df.values

array([['connoto99', 1953, 'Veterans', ..., 0, 'Y', 'Umpire'],
       ['klembi99', 1953, 'Veterans', ..., 0, 'Y', 'Umpire'],
       ['evansbi99', 1973, 'Veterans', ..., 0, 'Y', 'Umpire'],
       ...,
       ['durocle01', 1962, 'BBWAA', ..., 1, 'N', 'Manager'],
       ['durocle01', 1948, 'BBWAA', ..., 1, 'N', 'Manager'],
       ['stengca01', 1948, 'BBWAA', ..., 1, 'N', 'Manager']], dtype=object)

In [138]:
# Accessing a column as a Series
type(df.votes)

pandas.core.series.Series

In [139]:
df.votes.head()

0    0
1    0
2    0
3    0
4    0
Name: votes, dtype: int64

In [140]:
df.votes.mean()

48.60703883495145

In [141]:
# Accessing a row as a Series
s0 = df.loc[0]
type(s0)

pandas.core.series.Series

In [142]:
type(ps)

pandas.core.series.Series

In [143]:
s0

playerID    connoto99
yearID           1953
votedBy      Veterans
ballots             0
needed              0
votes               0
inducted            Y
category       Umpire
Name: 0, dtype: object

In [144]:
# Accessing values as a NumPy Array
df.values

array([['connoto99', 1953, 'Veterans', ..., 0, 'Y', 'Umpire'],
       ['klembi99', 1953, 'Veterans', ..., 0, 'Y', 'Umpire'],
       ['evansbi99', 1973, 'Veterans', ..., 0, 'Y', 'Umpire'],
       ...,
       ['durocle01', 1962, 'BBWAA', ..., 1, 'N', 'Manager'],
       ['durocle01', 1948, 'BBWAA', ..., 1, 'N', 'Manager'],
       ['stengca01', 1948, 'BBWAA', ..., 1, 'N', 'Manager']], dtype=object)

In [145]:
df.values[0]

array(['connoto99', 1953, 'Veterans', 0, 0, 0, 'Y', 'Umpire'],
      dtype=object)

In [146]:
df.values[:, 5]

array([0, 0, 0, ..., 1, 1, 1], dtype=object)

In [147]:
df.votes.values

array([0, 0, 0, ..., 1, 1, 1])

In [148]:
df.values[:, 5].mean()

48.60703883495145

In [149]:
df.votes.values.mean()

48.60703883495145

In [150]:
df.votes.describe()

count    4120.000000
mean       48.607039
std        83.531725
min         0.000000
25%         1.000000
50%         8.000000
75%        59.000000
max       555.000000
Name: votes, dtype: float64

### DataFrame VS SQL

In [151]:
# SELECT
# SELECT votedBy, votes, inducted, category FROM fame LIMIT 5;
df[['votedBy', 'votes', 'inducted', 'category']].head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>votedBy</th>
      <th>votes</th>
      <th>inducted</th>
      <th>category</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Veterans</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Veterans</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Veterans</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Veterans</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Veterans</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
    </tr>
  </tbody>
</table>
</div>

In [152]:
# WHERE
# SELECT * FROM fame WHERE category = 'Player' LIMIT 5;
df[df.category == 'Player'].head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>playerID</th>
      <th>yearID</th>
      <th>votedBy</th>
      <th>ballots</th>
      <th>needed</th>
      <th>votes</th>
      <th>inducted</th>
      <th>category</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>10</th>
      <td>maddugr01</td>
      <td>2014</td>
      <td>BBWAA</td>
      <td>571</td>
      <td>429</td>
      <td>555</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>11</th>
      <td>ripkeca01</td>
      <td>2007</td>
      <td>BBWAA</td>
      <td>545</td>
      <td>409</td>
      <td>537</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>12</th>
      <td>johnsra05</td>
      <td>2015</td>
      <td>BBWAA</td>
      <td>549</td>
      <td>412</td>
      <td>534</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>13</th>
      <td>gwynnto01</td>
      <td>2007</td>
      <td>BBWAA</td>
      <td>545</td>
      <td>409</td>
      <td>532</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>14</th>
      <td>glavito02</td>
      <td>2014</td>
      <td>BBWAA</td>
      <td>571</td>
      <td>429</td>
      <td>525</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
  </tbody>
</table>
</div>

In [153]:
# SELECT * FROM fame WHERE category = 'Player' AND inducted = 'N' LIMIT 5;
df[(df.category == 'Player') & (df.inducted == 'N')].head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>playerID</th>
      <th>yearID</th>
      <th>votedBy</th>
      <th>ballots</th>
      <th>needed</th>
      <th>votes</th>
      <th>inducted</th>
      <th>category</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>257</th>
      <td>biggicr01</td>
      <td>2014</td>
      <td>BBWAA</td>
      <td>571</td>
      <td>429</td>
      <td>427</td>
      <td>N</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>258</th>
      <td>blylebe01</td>
      <td>2010</td>
      <td>BBWAA</td>
      <td>539</td>
      <td>405</td>
      <td>400</td>
      <td>N</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>259</th>
      <td>alomaro01</td>
      <td>2010</td>
      <td>BBWAA</td>
      <td>539</td>
      <td>405</td>
      <td>397</td>
      <td>N</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>260</th>
      <td>riceji01</td>
      <td>2008</td>
      <td>BBWAA</td>
      <td>543</td>
      <td>408</td>
      <td>392</td>
      <td>N</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>261</th>
      <td>biggicr01</td>
      <td>2013</td>
      <td>BBWAA</td>
      <td>569</td>
      <td>427</td>
      <td>388</td>
      <td>N</td>
      <td>Player</td>
    </tr>
  </tbody>
</table>
</div>

In [154]:
# SELECT * FROM fame WHERE category IS NULL LIMIT 5;
df[df.category.isna()].head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>playerID</th>
      <th>yearID</th>
      <th>votedBy</th>
      <th>ballots</th>
      <th>needed</th>
      <th>votes</th>
      <th>inducted</th>
      <th>category</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
</div>

In [155]:
df.isna().values.any()

False

In [156]:
# GROUP BY
# SELECT category, COUNT(*) FROM fame GROUP BY category;
df.groupby('category').size()

category
Manager                74
Pioneer/Executive      39
Player               3997
Umpire                 10
dtype: int64

In [157]:
# SELECT yearid, AVG(needed), COUNT(*) FROM fame GROUP BY yearid LIMIT 5;
df.groupby('yearID').agg({'needed': np.mean, 'yearID': np.size}).head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>needed</th>
      <th>yearID</th>
    </tr>
    <tr>
      <th>yearID</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1936</th>
      <td>109.454545</td>
      <td>110</td>
    </tr>
    <tr>
      <th>1937</th>
      <td>144.601695</td>
      <td>118</td>
    </tr>
    <tr>
      <th>1938</th>
      <td>193.770492</td>
      <td>122</td>
    </tr>
    <tr>
      <th>1939</th>
      <td>193.460870</td>
      <td>115</td>
    </tr>
    <tr>
      <th>1942</th>
      <td>175.000000</td>
      <td>72</td>
    </tr>
  </tbody>
</table>
</div>

In [158]:
# SELECT yearid, category, AVG(needed), COUNT(*) FROM fame GROUP BY yearid, category LIMIT 5;
df.groupby(['yearID', 'category']).agg({'needed': np.mean, 'category': np.size}).head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>needed</th>
      <th>category</th>
    </tr>
    <tr>
      <th>yearID</th>
      <th>category</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1936</th>
      <th>Player</th>
      <td>109.454545</td>
      <td>110</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">1937</th>
      <th>Manager</th>
      <td>90.600000</td>
      <td>5</td>
    </tr>
    <tr>
      <th>Pioneer/Executive</th>
      <td>37.750000</td>
      <td>4</td>
    </tr>
    <tr>
      <th>Player</th>
      <td>151.000000</td>
      <td>109</td>
    </tr>
    <tr>
      <th>1938</th>
      <th>Manager</th>
      <td>197.000000</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
</div>

In [159]:
# JOIN
player_df = pd.read_csv('https://raw.githubusercontent.com/chirayukong/infsci2725-spring-2018/master/assignment-01/Players.csv')
player_df.columns = ['playerID', 'nameFirst', 'nameLast']
player_df.info()
player_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18847 entries, 0 to 18846
Data columns (total 3 columns):
playerID     18847 non-null object
nameFirst    18808 non-null object
nameLast     18847 non-null object
dtypes: object(3)
memory usage: 441.8+ KB


<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>playerID</th>
      <th>nameFirst</th>
      <th>nameLast</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>aardsda01</td>
      <td>David</td>
      <td>Aardsma</td>
    </tr>
    <tr>
      <th>1</th>
      <td>aaronha01</td>
      <td>Hank</td>
      <td>Aaron</td>
    </tr>
    <tr>
      <th>2</th>
      <td>aaronto01</td>
      <td>Tommie</td>
      <td>Aaron</td>
    </tr>
    <tr>
      <th>3</th>
      <td>aasedo01</td>
      <td>Don</td>
      <td>Aase</td>
    </tr>
    <tr>
      <th>4</th>
      <td>abadan01</td>
      <td>Andy</td>
      <td>Abad</td>
    </tr>
  </tbody>
</table>
</div>

In [160]:
# SELECT * FROM player WHERE nameFirst IS NULL LIMIT 5;
player_df[player_df.nameFirst.isna()].head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>playerID</th>
      <th>nameFirst</th>
      <th>nameLast</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1502</th>
      <td>bolan01</td>
      <td>NaN</td>
      <td>Boland</td>
    </tr>
    <tr>
      <th>1569</th>
      <td>booth01</td>
      <td>NaN</td>
      <td>Booth</td>
    </tr>
    <tr>
      <th>2614</th>
      <td>carroch01</td>
      <td>NaN</td>
      <td>Carroll</td>
    </tr>
    <tr>
      <th>3215</th>
      <td>colli01</td>
      <td>NaN</td>
      <td>Collins</td>
    </tr>
    <tr>
      <th>4810</th>
      <td>edwar01</td>
      <td>NaN</td>
      <td>Edwards</td>
    </tr>
  </tbody>
</table>
</div>

In [161]:
# INNER JOIN
# SELECT * FROM fame INNER JOIN player ON fame.playerID = player.playerID LIMIT 5;
pd.merge(df, player_df, on='playerID').head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>playerID</th>
      <th>yearID</th>
      <th>votedBy</th>
      <th>ballots</th>
      <th>needed</th>
      <th>votes</th>
      <th>inducted</th>
      <th>category</th>
      <th>nameFirst</th>
      <th>nameLast</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>connoto99</td>
      <td>1953</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Tommy</td>
      <td>Connolly</td>
    </tr>
    <tr>
      <th>1</th>
      <td>klembi99</td>
      <td>1953</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Bill</td>
      <td>Klem</td>
    </tr>
    <tr>
      <th>2</th>
      <td>evansbi99</td>
      <td>1973</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Billy</td>
      <td>Evans</td>
    </tr>
    <tr>
      <th>3</th>
      <td>conlajo01</td>
      <td>1974</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Jocko</td>
      <td>Conlan</td>
    </tr>
    <tr>
      <th>4</th>
      <td>hubbaca99</td>
      <td>1976</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Cal</td>
      <td>Hubbard</td>
    </tr>
  </tbody>
</table>
</div>

In [162]:
# INNER JOIN
# SELECT * FROM fame LEFT OUTER JOIN player ON fame.playerID = player.playerID LIMIT 5;
ldf = pd.merge(df, player_df, on='playerID', how='left')
ldf.head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>playerID</th>
      <th>yearID</th>
      <th>votedBy</th>
      <th>ballots</th>
      <th>needed</th>
      <th>votes</th>
      <th>inducted</th>
      <th>category</th>
      <th>nameFirst</th>
      <th>nameLast</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>connoto99</td>
      <td>1953</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Tommy</td>
      <td>Connolly</td>
    </tr>
    <tr>
      <th>1</th>
      <td>klembi99</td>
      <td>1953</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Bill</td>
      <td>Klem</td>
    </tr>
    <tr>
      <th>2</th>
      <td>evansbi99</td>
      <td>1973</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Billy</td>
      <td>Evans</td>
    </tr>
    <tr>
      <th>3</th>
      <td>conlajo01</td>
      <td>1974</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Jocko</td>
      <td>Conlan</td>
    </tr>
    <tr>
      <th>4</th>
      <td>hubbaca99</td>
      <td>1976</td>
      <td>Veterans</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Cal</td>
      <td>Hubbard</td>
    </tr>
  </tbody>
</table>
</div>

In [163]:
ldf.isnull().values.any()

False

In [164]:
# SELECT * FROM fame RIGHT OUTER JOIN player ON fame.playerID = player.playerID LIMIT 5;
rdf = pd.merge(df, player_df, on='playerID', how='right')
rdf.head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>playerID</th>
      <th>yearID</th>
      <th>votedBy</th>
      <th>ballots</th>
      <th>needed</th>
      <th>votes</th>
      <th>inducted</th>
      <th>category</th>
      <th>nameFirst</th>
      <th>nameLast</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>connoto99</td>
      <td>1953.0</td>
      <td>Veterans</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Tommy</td>
      <td>Connolly</td>
    </tr>
    <tr>
      <th>1</th>
      <td>klembi99</td>
      <td>1953.0</td>
      <td>Veterans</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Bill</td>
      <td>Klem</td>
    </tr>
    <tr>
      <th>2</th>
      <td>evansbi99</td>
      <td>1973.0</td>
      <td>Veterans</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Billy</td>
      <td>Evans</td>
    </tr>
    <tr>
      <th>3</th>
      <td>conlajo01</td>
      <td>1974.0</td>
      <td>Veterans</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Jocko</td>
      <td>Conlan</td>
    </tr>
    <tr>
      <th>4</th>
      <td>hubbaca99</td>
      <td>1976.0</td>
      <td>Veterans</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Cal</td>
      <td>Hubbard</td>
    </tr>
  </tbody>
</table>
</div>

In [165]:
rdf.isnull().values.any()

True

In [166]:
rdf[rdf.yearID.isna()].head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>playerID</th>
      <th>yearID</th>
      <th>votedBy</th>
      <th>ballots</th>
      <th>needed</th>
      <th>votes</th>
      <th>inducted</th>
      <th>category</th>
      <th>nameFirst</th>
      <th>nameLast</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>4120</th>
      <td>aardsda01</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>David</td>
      <td>Aardsma</td>
    </tr>
    <tr>
      <th>4121</th>
      <td>aaronto01</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Tommie</td>
      <td>Aaron</td>
    </tr>
    <tr>
      <th>4122</th>
      <td>aasedo01</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Don</td>
      <td>Aase</td>
    </tr>
    <tr>
      <th>4123</th>
      <td>abadan01</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Andy</td>
      <td>Abad</td>
    </tr>
    <tr>
      <th>4124</th>
      <td>abadfe01</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Fernando</td>
      <td>Abad</td>
    </tr>
  </tbody>
</table>
</div>

In [167]:
# SELECT * FROM fame OUTER JOIN player ON fame.playerID = player.playerID LIMIT 5;
fdf = pd.merge(df, player_df, on='playerID', how='outer')
fdf.head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>playerID</th>
      <th>yearID</th>
      <th>votedBy</th>
      <th>ballots</th>
      <th>needed</th>
      <th>votes</th>
      <th>inducted</th>
      <th>category</th>
      <th>nameFirst</th>
      <th>nameLast</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>connoto99</td>
      <td>1953.0</td>
      <td>Veterans</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Tommy</td>
      <td>Connolly</td>
    </tr>
    <tr>
      <th>1</th>
      <td>klembi99</td>
      <td>1953.0</td>
      <td>Veterans</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Bill</td>
      <td>Klem</td>
    </tr>
    <tr>
      <th>2</th>
      <td>evansbi99</td>
      <td>1973.0</td>
      <td>Veterans</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Billy</td>
      <td>Evans</td>
    </tr>
    <tr>
      <th>3</th>
      <td>conlajo01</td>
      <td>1974.0</td>
      <td>Veterans</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Jocko</td>
      <td>Conlan</td>
    </tr>
    <tr>
      <th>4</th>
      <td>hubbaca99</td>
      <td>1976.0</td>
      <td>Veterans</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>Y</td>
      <td>Umpire</td>
      <td>Cal</td>
      <td>Hubbard</td>
    </tr>
  </tbody>
</table>
</div>

In [168]:
fdf.isnull().values.any()

True

In [169]:
fdf[fdf.nameFirst.isna()].head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>playerID</th>
      <th>yearID</th>
      <th>votedBy</th>
      <th>ballots</th>
      <th>needed</th>
      <th>votes</th>
      <th>inducted</th>
      <th>category</th>
      <th>nameFirst</th>
      <th>nameLast</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>5523</th>
      <td>bolan01</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Boland</td>
    </tr>
    <tr>
      <th>5581</th>
      <td>booth01</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Booth</td>
    </tr>
    <tr>
      <th>6562</th>
      <td>carroch01</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Carroll</td>
    </tr>
    <tr>
      <th>7118</th>
      <td>colli01</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Collins</td>
    </tr>
    <tr>
      <th>8605</th>
      <td>edwar01</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>Edwards</td>
    </tr>
  </tbody>
</table>
</div>

In [170]:
# Top N rows with offset
# SELECT * FROM fame ORDER BY votes DESC LIMIT 10 OFFSET 5; -- MySQL
df.nlargest(10+5, columns='votes').tail(10)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>playerID</th>
      <th>yearID</th>
      <th>votedBy</th>
      <th>ballots</th>
      <th>needed</th>
      <th>votes</th>
      <th>inducted</th>
      <th>category</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>15</th>
      <td>alomaro01</td>
      <td>2011</td>
      <td>BBWAA</td>
      <td>581</td>
      <td>436</td>
      <td>523</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>16</th>
      <td>henderi01</td>
      <td>2009</td>
      <td>BBWAA</td>
      <td>539</td>
      <td>405</td>
      <td>511</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>17</th>
      <td>martipe02</td>
      <td>2015</td>
      <td>BBWAA</td>
      <td>549</td>
      <td>412</td>
      <td>500</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>18</th>
      <td>larkiba01</td>
      <td>2012</td>
      <td>BBWAA</td>
      <td>573</td>
      <td>430</td>
      <td>495</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>19</th>
      <td>ryanno01</td>
      <td>1999</td>
      <td>BBWAA</td>
      <td>497</td>
      <td>373</td>
      <td>491</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>20</th>
      <td>brettge01</td>
      <td>1999</td>
      <td>BBWAA</td>
      <td>497</td>
      <td>373</td>
      <td>488</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>21</th>
      <td>thomafr04</td>
      <td>2014</td>
      <td>BBWAA</td>
      <td>571</td>
      <td>429</td>
      <td>478</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>22</th>
      <td>boggswa01</td>
      <td>2005</td>
      <td>BBWAA</td>
      <td>516</td>
      <td>387</td>
      <td>474</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>23</th>
      <td>gossari01</td>
      <td>2008</td>
      <td>BBWAA</td>
      <td>543</td>
      <td>408</td>
      <td>466</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
    <tr>
      <th>24</th>
      <td>blylebe01</td>
      <td>2011</td>
      <td>BBWAA</td>
      <td>581</td>
      <td>436</td>
      <td>463</td>
      <td>Y</td>
      <td>Player</td>
    </tr>
  </tbody>
</table>
</div>